name: Noting
options:
  bundleIdPrefix: com.artem
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

targets:
  Noting:
    type: application
    platform: iOS
    supportedDestinations: [iOS, macOS]
    sources:
      - Noting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.artem.noting
        DEVELOPMENT_TEAM: D3DARN693A
        INFOPLIST_KEY_CFBundleDisplayName: Noting
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        GENERATE_INFOPLIST_FILE: true
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    info:
      path: Noting/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - noting
        UILaunchScreen: {}
